version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_DATABASE: ekan
      MYSQL_USER: ederp
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
